# Generated by Django 3.1.1 on 2022-09-09 09:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=30, unique=True)),
            ],
        ),
    ]
